### ISSUE TITLE
Add note on optimization to single-stepping.md

### ISSUE THREAD

**Issue by johnzl-777** [jlpteaching/dinocpu-sq20#13]
I ran into an issue during one of the labs where I was trying to dump the hazard unit but not all the signals were showing up. 

It was pointed out on Campuswire that this is just due to the aggressive optimizing nature of Chisel.

I was wondering if it would be a good idea to add this somewhere in the `single-stepping.md` documentation as well as the `printf()` fix which forces Chisel to keep the wire in place. 

If permitted, I'd like to add that portion in myself, near the bottom of the document.

**Comment by powerjg** [comment]
Please do!

**Comment by johnzl-777** [comment]
PR has been merged, closing the issue :)
