### ISSUE TITLE
Linux installation instructions linked for installing Singularity does not install correct version

### ISSUE THREAD

**Issue by UnHumbleBen** [jlpteaching/dinocpu-sq20#2]
The instructions for installing on Linux provided from [the docs](https://github.com/jlpteaching/dinocpu-sq20/blob/master/documentation/singularity.md#using-your-own-machine):

>For Linux, I suggest using the provided packages, not building from source.
> Details are available [here](https://www.sylabs.io/guides/3.0/user-guide/installation.html#install-the-debian-ubuntu-package-using-apt).
> **Be sure to use version 3 of Singularity, as it's the only version that supports the Singularity library!**

The instructions lead to installing 2.5.x or 2.6.x. There is currently [**no** stable packages for Singularity 3.0](http://neuro.debian.net/pkgs/singularity-container.html) so it is **not** possible to install from packages. Only option is building from source or using CSIF.

**Comment by powerjg** [comment]
Thanks! @JulianToya, could you update the docs here to state that if you install singularity you must build from source?
