### ISSUE TITLE
Test cases passing despite not implementing proper behavior

### ISSUE THREAD

**Issue by johnzl-777** [jlpteaching/dinocpu-sq20#6]
I'm currently using the solution files from Lab 1 to continue work for Lab 2.

If one doesn't make any modifications to the `alucontrol.scala` solution in anticipation of I-type instructions, it still passes all nine cases.

This shouldn't happen considering that in immediate instructions, we are supposed to completely ignore the `funct7` data.

If I am granted permission, I would like to add a test case(or cases) that trigger a failure (perhaps by giving the immediate data something that, if someone had not ignored `funct7`, would induce failure)

**Comment by powerjg** [comment]
That would be *great*!

The best way to do that would be to clone the [dinocpu repo](https://github.com/jlpteaching/dinocpu) and create a [PR there](https://github.com/jlpteaching/dinocpu/pulls). We can then merge those changes into this repo.

Alternatively, you can create a PR into this repo. Just be very careful not to put any answers in your clone :).

**Comment by johnzl-777** [comment]
[This PR](https://github.com/jlpteaching/dinocpu/pull/129) has the test case and has been approved by @JulianToya . Once it's merged in I'll go ahead and close the issue.

**Comment by johnzl-777** [comment]
The PR has been merged, I'm gonna go ahead and close this issue 😎
